### ISSUE TITLE
when setting a whitelist kubernetes logging breaks

### ISSUE THREAD

**Issue by josehelps** [splunk/attack_range_cloud#2]
This is due to the cluster pod being unable to reach the splunk server on HEC due to the new security group ACLs. For example the generated splunk k8s config points to the splunk server public IP on port 80808 my machine is able to reach it but the cluster is not:

```
┌──[jhernandez@jhernandez-mbp-cb9a8]─[~/workspace/attack_range_cloud on  master!]
└── # cat kubernetes/splunkk8s.yaml
global:
  splunk:
    hec:
      token: xxxxxxx
      host: 3.89.11.xx
      port: 8088
      indexName: kubernetes
      insecureSSL: true
      protocol: https
splunk-kubernetes-metrics:
  splunk:
    hec:
      indexName: kubernetes-metrics%
```
